{% set name = "drf-haystack" %}
{% set version = "1.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34c4307a5d09c51dc8ed60ba397e84e7ffc060d33a3c0ecbea475f17fa7a4a44

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - django >=1.11,<2.1
    - django-haystack >=2.8
    - djangorestframework >=3.7

test:
  imports:
    - drf_haystack

about:
  home: https://drf-haystack.readthedocs.io/en/latest/index.html#
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Haystack for Django REST Framework'
  description: |
    Small library which tries to simplify integration of Haystack with Django REST Framework.
  doc_url: https://drf-haystack.readthedocs.io/en/latest/index.html#
  dev_url: https://github.com/inonit/drf-haystack

extra:
  recipe-maintainers:
    - scopatz
