{% set name = "drf-haystack" %}
{% set version = "1.8.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 978827af342a10e2ab0ba626c44d5ee843d3771cfdb528b1b9012909b2f21aeb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - django >=2.2,<3.2
    - django-haystack >=2.8,<3.1
    - djangorestframework >=3.7,<3.13

test:
  imports:
    - drf_haystack

about:
  home: https://drf-haystack.readthedocs.io/en/latest/index.html#
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Haystack for Django REST Framework
  description: |
    Small library which tries to simplify integration of Haystack with Django REST Framework.
  doc_url: https://drf-haystack.readthedocs.io/en/latest/index.html#
  dev_url: https://github.com/inonit/drf-haystack

extra:
  recipe-maintainers:
    - scopatz
    - xmnlab
