{% set name = "drf-haystack" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a51938ff66301b5a25349b3b2cb745d5c20144887301e319466c980a8995bd7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - django >=1.11,<2.1
    - django-haystack >=2.8
    - djangorestframework >=3.7

test:
  imports:
    - drf_haystack

about:
  home: https://drf-haystack.readthedocs.io/en/latest/index.html#
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Haystack for Django REST Framework'
  description: |
    Small library which tries to simplify integration of Haystack with Django REST Framework.
  doc_url: https://drf-haystack.readthedocs.io/en/latest/index.html#
  dev_url: https://github.com/inonit/drf-haystack

extra:
  recipe-maintainers:
    - scopatz
